services:
  app:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fakebook-java?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass

  db:
    image: mysql:latest
    build:
      context: .
      dockerfile: db/Dockerfile
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: fakebook-java
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
